### ISSUE TITLE
MIDI Messages are not all 3 bytes

### ISSUE THREAD

**Issue by fcanas** [mkj-is/CombineMIDI#7]
Some useful MIDI messages are 2 bytes (see program change), and some less common ones are even one byte.
https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

I've created a fork with some different approaches that suit my needs. I'm happy to contribute them back, but I understand the changes are somewhat dramatic. https://github.com/fcanas/CombineMIDI

**Comment by mkj-is** [comment]
Thanks for pointing up this issue!

If we wanted to pursue this I see some things what we would need to do:

- [ ] Update the documentation
- [x] Update the logic of [chunking messages into three bytes](https://github.com/mkj-is/CombineMIDI/blob/main/Sources/CombineMIDI/MIDISubscription.swift#L40)

There is one point for discussion: Modelling the messages as enum with associated values makes the code much more complicated – I believe it would be enough if the second and third byte were optional or if they were filled with zeros. (I can see some developer experience improvements in your implementation.)

**Comment by fcanas** [comment]
An approach without modeling messages in an enum might look like this. It's not exhaustive, but it adds some more messages, and fills out support for 1, 2, and 3 byte messages. https://github.com/fcanas/CombineMIDI/commit/064f6f1bdf4684693a80c57ed2c1d8552b72eb4b

There's some complexity in dealing with a byte stream and ensuring proper message construction. I'm sure there are other approaches, but this is the one that occurred to me first.

Possibly a `MIDIMessage` should store its bytes as its sole representation, with convenience `status`, and optional `channel`, and `data` accessors.

The risk in keeping an internal 3 byte model, whether contiguous or restructured into various properties, is that more complexity would need to be added if the model were to be serialized. 1 and 2 byte messages are not zero-padded when transmitted.

On the use-side, I personally like the richer enum modeling for message as I can use the API without looking up MIDI documentation. I absolutely understand if you're not a fan, and I'm also open to other approaches.

**Comment by mkj-is** [comment]
Thanks for your work!

Can you open a PR? I think your solution is great – I might just add some more documentation and release it afterwards.

> There's some complexity in dealing with a byte stream and ensuring proper message construction. I'm sure there are other approaches, but this is the one that occurred to me first.

I might have some ideas for improvements, but we don't have to implement them. Your solution works fine.

> Possibly a MIDIMessage should store its bytes as its sole representation, with convenience status, and optional channel, and data accessors.

That is a good idea, but again, I don't see it as a necessary change.

> The risk in keeping an internal 3 byte model, whether contiguous or restructured into various properties, is that more complexity would need to be added if the model were to be serialized. 1 and 2 byte messages are not zero-padded when transmitted.

I agree this would be solved by storing the messsage as a byte array internally.

> On the use-side, I personally like the richer enum modeling for message as I can use the API without looking up MIDI documentation. I absolutely understand if you're not a fan, and I'm also open to other approaches.

I think about the rich enum as an extension of the basic model. It can make some operations on the MIDI messages more complicated – like filtering. I am not against it, but I would like to keep the basic representation and add the rich enum if it ergonomically suits the user better.
